name: build-and-test
on:
  workflow_call: {}
runs:
  using: composite
  steps:
    - uses: actions/setup-python@v2
      with:
        python-version: "3.7"
    - run: curl -sSL https://install.python-poetry.org | python3 -
      shell: bash
    - run: poetry install
      shell: bash
    - run: poetry run pytest
      shell: bash
      working-directory: ./tests
    - run: poetry run mypy aws_lambda_api_event_utils --ignore-missing-imports
      shell: bash
    - run: poetry build
      shell: bash
